"use client";
import { useMemo,useState } from "react";
import { Banknote,CheckCircle2,Landmark,Plus,ReceiptText,WalletCards } from "lucide-react";
import { Button,Input,Select,Textarea } from "@/components/ui/form-primitives";
import { baixarConta,criarBanco,criarCentro,criarConta } from "./actions";
const brl=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export function ContasPagarClient({contas,bancos,centros,socios,caixa}:{contas:any[];bancos:any[];centros:any[];socios:any[];caixa:any[]}){
 const [tab,setTab]=useState<"conta"|"banco"|"centro">("conta"); const [pessoal,setPessoal]=useState(false);
 const resumo=useMemo(()=>{const abertas=contas.filter(c=>c.status==='aberta'); const mes=new Date().toISOString().slice(0,7); const pagas=contas.filter(c=>c.status==='paga'&&c.competencia===mes); const pessoalMes=pagas.filter(c=>c.pago_pessoalmente); const porSocio=new Map<string,number>(); pessoalMes.forEach(c=>porSocio.set(c.socio_pagador_usuario_id,(porSocio.get(c.socio_pagador_usuario_id)||0)+Number(c.valor))); const total=[...porSocio.values()].reduce((a,b)=>a+b,0); return {abertas:abertas.reduce((a,c)=>a+Number(c.valor),0),pagas:pagas.reduce((a,c)=>a+Number(c.valor),0),pessoal:total,ajustes:[...porSocio.entries()].map(([id,v])=>({nome:socios.find(s=>s.id===id)?.nome||"Sócio",saldo:v-total/Math.max(porSocio.size,1)}))};},[contas,socios]);
 const saldo=caixa.reduce((a,m)=>a+(m.tipo_movimento==='entrada'?Number(m.valor):-Number(m.valor)),0);
 return <div className="mx-auto max-w-7xl space-y-6 pb-10"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-700">Financeiro operacional</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">Contas a pagar e caixa</h1><p className="mt-2 text-slate-500">Lance despesas, marque quem pagou e veja o ajuste justo entre os sócios.</p></header>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["A pagar",resumo.abertas,"bg-rose-600",ReceiptText],["Pagas no mês",resumo.pagas,"bg-emerald-600",CheckCircle2],["Pago pessoalmente",resumo.pessoal,"bg-amber-500",WalletCards],["Saldo de caixa",saldo,"bg-blue-700",Banknote]].map(([l,v,c,I]:any)=>{const Icon=I;return <div key={l} className={`${c} rounded-2xl p-5 text-white shadow-lg`}><Icon className="h-7 w-7 opacity-80"/><p className="mt-5 text-sm font-semibold opacity-90">{l}</p><p className="mt-1 text-3xl font-black">{brl(v)}</p></div>})}</div>
 <div className="flex gap-2 overflow-x-auto pb-1">{[["conta","Nova despesa",Plus],["banco","Cadastrar banco",Landmark],["centro","Centro de custo",ReceiptText]].map(([id,l,I]:any)=>{const Icon=I;return <button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-5 py-3 font-bold ${tab===id?"bg-slate-950 text-white":"bg-slate-100 text-slate-700"}`}><Icon className="h-5 w-5"/>{l}</button>})}</div>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{tab==='conta'?<form action={criarConta} className="grid gap-3 md:grid-cols-3"><Input name="descricao" required placeholder="O que precisa ser pago? *"/><Input name="fornecedor" placeholder="Fornecedor"/><Input name="valor" required type="number" step="0.01" min="0.01" placeholder="Valor (R$) *"/><Input name="vencimento" required type="date"/><Select name="centro"><option value="">Centro de custo</option>{centros.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</Select><Select name="banco"><option value="">Conta bancária</option>{bancos.map(b=><option key={b.id} value={b.id}>{b.nome}</option>)}</Select><label className="flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-sm font-bold text-amber-900 md:col-span-2"><input name="pessoal" type="checkbox" checked={pessoal} onChange={e=>setPessoal(e.target.checked)}/> Paguei pessoalmente como sócio</label>{pessoal?<Select name="socio" required><option value="">Quem pagou?</option>{socios.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</Select>:null}<Textarea name="obs" className="md:col-span-2" placeholder="Observação (opcional)"/><Button className="min-h-12 bg-blue-700 text-base hover:bg-blue-800">Adicionar conta</Button></form>:tab==='banco'?<form action={criarBanco} className="grid gap-3 md:grid-cols-4"><Input name="nome" required placeholder="Nome para exibir *"/><Input name="banco" placeholder="Banco"/><Input name="agencia" placeholder="Agência"/><Input name="conta" placeholder="Conta (ex.: **** 1234)"/><Button className="min-h-12 md:col-span-4">Salvar banco</Button></form>:<form action={criarCentro} className="grid gap-3 md:grid-cols-3"><Input name="nome" required placeholder="Nome do centro *"/><Input name="codigo" placeholder="Código"/><Button className="min-h-12">Salvar centro</Button></form>}</section>
 <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold text-slate-900">Despesas</h2></div><div className="divide-y">{contas.length===0?<p className="p-8 text-center text-slate-500">Nenhuma despesa cadastrada ainda.</p>:contas.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-bold text-slate-900">{c.descricao}</p><p className="text-sm text-slate-500">Vence em {new Date(c.vencimento+"T12:00:00").toLocaleDateString("pt-BR")}{c.pago_pessoalmente?" · Pago por sócio":""}</p></div><div className="flex items-center gap-3"><b className="text-slate-900">{brl(Number(c.valor))}</b>{c.status==='aberta'?<Button onClick={()=>baixarConta(c.id)} className="bg-emerald-600 hover:bg-emerald-700">Dar baixa</Button>:<span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">Paga</span>}</div></div>)}</div></section><section className="rounded-2xl bg-slate-950 p-5 text-white shadow-lg"><h2 className="font-bold">Fechamento entre sócios</h2><p className="mt-1 text-sm text-slate-400">Somente despesas marcadas como pagas pessoalmente neste mês.</p><div className="mt-5 space-y-3">{resumo.ajustes.length===0?<p className="rounded-xl bg-white/10 p-4 text-sm text-slate-300">Marque uma despesa como paga pessoalmente para ver a compensação.</p>:resumo.ajustes.map(a=><div key={a.nome} className="rounded-xl bg-white/10 p-4"><p className="font-semibold">{a.nome}</p><p className="mt-1 text-sm text-slate-300">{a.saldo>0?`Deve receber ${brl(a.saldo)} dos demais / empresa.`:a.saldo<0?`Deve repassar ${brl(-a.saldo)} para equalizar.`:"Está equilibrado."}</p></div>)}</div></section></div></div> }
