import Link from "next/link";
import { Search, Plus, MoreHorizontal, UsersRound, BadgeCheck, WalletCards, FileSpreadsheet } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { getCurrentTenantContext } from "@/lib/tenant/context";

type Cliente = { id: string; tipo_pessoa: "PF" | "PJ"; nome: string; cpf_cnpj: string | null; telefone: string | null; status: string; participante_comercial_id: string | null; pendencias_cadastro: string[] };
type Participante = { id: string; nome: string; nome_exibicao: string | null };

const document = (value: string | null) => value || "Não informado";

export default async function ClientesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const { empresaAtiva } = await getCurrentTenantContext(); const supabase = await createClient();
  if (!empresaAtiva) return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900">Selecione uma empresa para consultar clientes.</div>;
  const busca = params.busca?.trim() ?? ""; const tipo = params.tipo ?? ""; const status = params.status ?? "";
  let query = supabase.from("clientes").select("id,tipo_pessoa,nome,cpf_cnpj,telefone,status,participante_comercial_id,pendencias_cadastro").eq("empresa_id", empresaAtiva.id).order("nome").limit(100);
  if (tipo === "PF" || tipo === "PJ") query = query.eq("tipo_pessoa", tipo); if (status === "ativo" || status === "inativo") query = query.eq("status", status);
  if (busca) query = query.or(`nome.ilike.%${busca}%,cpf_cnpj.ilike.%${busca}%,telefone.ilike.%${busca}%`);
  const [clientesResult, participantesResult, cotasResult] = await Promise.all([query, supabase.from("participantes_comerciais").select("id,nome,nome_exibicao").eq("empresa_id", empresaAtiva.id), supabase.from("cotas_definitivas").select("venda_id,vendas!inner(cliente_id)").eq("empresa_id", empresaAtiva.id)]);
  const clientes = (clientesResult.data ?? []) as Cliente[]; const participantes = (participantesResult.data ?? []) as Participante[];
  const consultores = new Map(participantes.map((p) => [p.id, p.nome_exibicao || p.nome]));
  const cotasPorCliente = new Map<string, number>(); for (const row of (cotasResult.data ?? []) as unknown as Array<{ vendas: Array<{ cliente_id: string | null }> | null }>) { const id = row.vendas?.[0]?.cliente_id; if (id) cotasPorCliente.set(id, (cotasPorCliente.get(id) ?? 0) + 1); }
  return <main className="space-y-6 pb-10"><section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 px-6 py-7 text-white shadow-xl sm:px-8"><div className="absolute -right-16 -top-14 h-52 w-52 rounded-full bg-cyan-400/20 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">ERP operacional</p><h1 className="mt-2 text-3xl font-black tracking-tight">Clientes</h1><p className="mt-2 max-w-xl text-sm text-slate-300">Cadastro real, separado de Leads e Propostas. Acompanhe pessoas, empresas e suas cotas efetivadas.</p></div><div className="flex flex-wrap gap-3"><Link href="/erp/clientes/importar" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-bold text-white hover:bg-white/20"><FileSpreadsheet size={19}/> Importar legados</Link><Link href="/erp/clientes/novo" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-slate-950 shadow-lg shadow-cyan-500/20 transition hover:bg-cyan-300"><Plus size={19}/> Novo cliente</Link></div></div></section>
    <section className="grid gap-3 sm:grid-cols-3"><Metric icon={<UsersRound size={19}/>} label="Clientes encontrados" value={clientes.length}/><Metric icon={<BadgeCheck size={19}/>} label="Cadastros ativos" value={clientes.filter((item) => item.status === "ativo").length}/><Metric icon={<WalletCards size={19}/>} label="Cotas vinculadas" value={[...cotasPorCliente.values()].reduce((a,b) => a+b, 0)}/></section>
    <form className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 lg:grid-cols-[1fr_160px_160px_auto]"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input name="busca" defaultValue={busca} placeholder="Buscar por nome, CPF/CNPJ ou telefone" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/></label><select name="tipo" defaultValue={tipo} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">PF e PJ</option><option value="PF">Pessoa física</option><option value="PJ">Pessoa jurídica</option></select><select name="status" defaultValue={status} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">Todos os status</option><option value="ativo">Ativos</option><option value="inativo">Inativos</option></select><button className="h-11 rounded-xl bg-slate-900 px-5 text-sm font-bold text-white hover:bg-slate-700">Filtrar</button></div></form>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-900">Carteira de clientes</h2><p className="mt-0.5 text-sm text-slate-500">Somente clientes cadastrados ou originados de contrato assinado.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{clientes.length} registros</span></div><div className="overflow-x-auto"><table className="min-w-[800px] w-full text-left text-sm"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Tipo</th><th className="px-5 py-3">Cliente</th><th className="px-5 py-3">CPF/CNPJ</th><th className="px-5 py-3">Telefone</th><th className="px-5 py-3 text-center">Cotas</th><th className="px-5 py-3">Consultor</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"><span className="sr-only">Ações</span></th></tr></thead><tbody>{clientes.length ? clientes.map((cliente) => <tr key={cliente.id} className="border-t border-slate-100 transition hover:bg-blue-50/40"><td className="px-5 py-4"><span className={`rounded-lg px-2.5 py-1 text-xs font-black ${cliente.tipo_pessoa === "PJ" ? "bg-violet-100 text-violet-700" : "bg-cyan-100 text-cyan-700"}`}>{cliente.tipo_pessoa}</span></td><td className="px-5 py-4"><Link href={`/erp/clientes/${cliente.id}`} className="font-bold text-slate-900 hover:text-blue-700">{cliente.nome}</Link></td><td className="px-5 py-4 text-slate-600">{document(cliente.cpf_cnpj)}</td><td className="px-5 py-4 text-slate-600">{cliente.telefone || "—"}</td><td className="px-5 py-4 text-center font-bold text-slate-800">{cotasPorCliente.get(cliente.id) ?? 0}</td><td className="px-5 py-4 text-slate-600">{cliente.participante_comercial_id ? consultores.get(cliente.participante_comercial_id) ?? "Consultor" : "Não atribuído"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${cliente.status === "ativo" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{cliente.status === "ativo" ? "Ativo" : "Inativo"}</span></td><td className="px-5 py-4"><Link href={`/erp/clientes/${cliente.id}`} aria-label={`Ver ${cliente.nome}`} className="inline-flex rounded-lg border border-slate-200 p-2 text-slate-600 hover:border-blue-300 hover:text-blue-700"><MoreHorizontal size={18}/></Link></td></tr>) : <tr><td colSpan={8} className="px-6 py-14 text-center"><UsersRound className="mx-auto text-slate-300" size={34}/><p className="mt-3 font-bold text-slate-700">Nenhum cliente encontrado</p><p className="mt-1 text-sm text-slate-500">Cadastre um cliente ou aguarde uma contratação ser marcada como assinada.</p></td></tr>}</tbody></table></div></section></main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-700">{icon}</span><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="text-2xl font-black text-slate-900">{value}</p></div></div></div>; }
