import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function ProgramaPlatformPage({params}:{params:Promise<{id:string;programaId:string}>}) {
  const {id,programaId}=await params; const db=await createClient();
  const {data}=await db.from("comissao_programas").select("id,nome,descricao,versao,status,ativo,administradora_id,administradora:administradoras(nome,nome_fantasia),empresa:empresas(nome_fantasia),regras:comissao_regras_franquia(id,versao,percentual_total_comissao,base_calculo,vigencia_inicio,vigencia_fim,configuracao_homologada,origem_configuracao,tipo:administradora_tipos(nome),modalidade:administradora_modalidades_comissao(nome),curva:administradora_curvas_estorno(nome,versao),etapas:comissao_regra_etapas(id,ordem,tipo_gatilho,mes_relativo,nome,percentual_venda))").eq("id",programaId).eq("administradora_id",id).maybeSingle();
  if(!data)notFound(); const regras=(data.regras??[]) as unknown as Array<{id:string;versao:number;percentual_total_comissao:number|null;base_calculo:string;vigencia_inicio:string;vigencia_fim:string|null;configuracao_homologada:boolean;origem_configuracao:string;tipo:{nome?:string}|null;modalidade:{nome?:string}|null;curva:{nome?:string;versao?:number}|null;etapas:Array<{id:string;ordem:number;tipo_gatilho:string;mes_relativo:number|null;nome:string;percentual_venda:number}>}>;
  const admin=data.administradora as {nome?:string;nome_fantasia?:string}|null;
  return <div className="space-y-6"><header><Link href={`/platform/administradoras/${id}?tab=programas`} className="text-sm font-bold text-cyan-700">← Programas da Administradora</Link><p className="mt-4 text-xs font-bold uppercase tracking-widest text-cyan-600">Platform · Programa oficial</p><h1 className="text-3xl font-bold">{data.nome}</h1><p className="text-slate-500">{admin?.nome_fantasia||admin?.nome} · versão {data.versao} · {data.status}</p></header>
    <div className="rounded-xl border border-cyan-200 bg-cyan-50 p-4"><strong>{data.status==="RASCUNHO"?"RASCUNHO — ainda não participa do motor de novas vendas.":"Programa versionado"}</strong><p className="text-sm">Regras homologadas/usadas não são editadas destrutivamente; a evolução ocorre por nova versão.</p></div>
    <section className="grid gap-4 md:grid-cols-4">{[["Administradora",admin?.nome_fantasia||admin?.nome],["Status",data.status],["Versão",data.versao],["Franquia",(data.empresa as {nome_fantasia?:string}|null)?.nome_fantasia]].map(([l,v])=><article key={String(l)} className="rounded-xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">{l}</p><p className="mt-2 font-bold">{v||"—"}</p></article>)}</section>
    {regras.map(r=><article key={r.id} className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{r.tipo?.nome||"Todos os tipos"} · {r.modalidade?.nome||"Todas as modalidades"}</h2><p className="text-sm text-slate-500">Vigência {r.vigencia_inicio} → {r.vigencia_fim||"aberta"}</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${r.configuracao_homologada?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{r.configuracao_homologada?"HOMOLOGADA":"RASCUNHO"}</span></div><dl className="mt-5 grid gap-3 md:grid-cols-3"><div><dt className="text-xs uppercase text-slate-500">Comissão total</dt><dd className="font-bold">{r.percentual_total_comissao??"—"}%</dd></div><div><dt className="text-xs uppercase text-slate-500">Curva de Estorno</dt><dd>{r.curva?`${r.curva.nome} · v${r.curva.versao}`:"Nenhuma"}</dd></div><div><dt className="text-xs uppercase text-slate-500">Origem</dt><dd>{r.origem_configuracao}</dd></div></dl><h3 className="mt-6 font-bold">Cronograma</h3><div className="mt-2 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Ordem</th><th>Gatilho</th><th>Mês</th><th>Etapa</th><th>Percentual</th></tr></thead><tbody>{r.etapas.sort((a,b)=>a.ordem-b.ordem).map(e=><tr key={e.id} className="border-b"><td className="p-2">{e.ordem}</td><td>{e.tipo_gatilho}</td><td>{e.mes_relativo??"Contemplação"}</td><td>{e.nome}</td><td>{e.percentual_venda}%</td></tr>)}</tbody></table></div></article>)}
  </div>;
}
