"use client";

import { useState } from "react";
import { Eye, Plus, Trash2, UserPlus, Users } from "lucide-react";
import { Button, Input, Label, Textarea, surfaceInputDarkSlate } from "@/components/ui/form-primitives";
import { MoneyInput } from "@/components/ui/money-input";
import { digitsOnlyPhone, formatCpfBrInput, formatCurrency, formatWhatsappBrInput } from "@/lib/utils/format";
import { TIPOS_CREDITO_PUBLICO } from "@/lib/leads/tipo-credito";
import { cn } from "@/lib/utils/cn";

type Aba = "indicar" | "programa" | "visualizar";
type Indicado = { id:string; nome:string; whatsapp:string; tipoCredito:string; valorCredito:number|null; observacao:string };
type Resultado = { id:string; nome:string; status:string; criadoEm:string; valorVenda:number|null };
const novoIndicado = ():Indicado => ({id:crypto.randomUUID(),nome:"",whatsapp:"",tipoCredito:"",valorCredito:null,observacao:""});
const STATUS:Record<string,string>={PENDENTE:"Pendente",VENDA_REALIZADA:"Venda realizada",COMISSAO_PREVISTA:"Comissão prevista",DISPONIVEL_PAGAMENTO:"Disponível para pagamento",PAGA:"Paga",CANCELADA:"Cancelada"};

export function IndicacaoForm({ origem }:{ origem?:string|null }) {
  const [aba,setAba]=useState<Aba>("indicar"),[loading,setLoading]=useState(false),[erro,setErro]=useState<string|null>(null),[sucesso,setSucesso]=useState<string|null>(null);
  const [indicadorId,setIndicadorId]=useState<string|null>(null),[indicadorNome,setIndicadorNome]=useState(""),[indicadorTelefone,setIndicadorTelefone]=useState(""),[buscaCpf,setBuscaCpf]=useState("");
  const [indicados,setIndicados]=useState<Indicado[]>([novoIndicado()]),[convidar,setConvidar]=useState(false);
  const [cadastro,setCadastro]=useState({nome:"",cpf:"",telefone:"",chavePix:"",empresaTrabalho:""});
  const [cpfConsulta,setCpfConsulta]=useState(""),[resultados,setResultados]=useState<Resultado[]>([]),[consultado,setConsultado]=useState(false);
  const api=async(payload:Record<string,unknown>)=>{const r=await fetch("/api/public/programa-indicacao",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha na operação");return d;};
  const trocar=(v:Aba)=>{setAba(v);setErro(null);setSucesso(null)};
  async function localizar(){setLoading(true);setErro(null);try{const d=await api({acao:"localizar",cpf:buscaCpf,telefone:indicadorTelefone});if(d.encontrado){setIndicadorId(d.indicadorId);setIndicadorNome(d.nome);setSucesso(`Indicador localizado: ${d.nome}`)}else{setIndicadorId(null);setSucesso("Cadastro não localizado. Informe nome completo e telefone para continuar.")}}catch(e){setErro(e instanceof Error?e.message:"Erro")}finally{setLoading(false)}}
  async function cadastrar(e:React.FormEvent){e.preventDefault();setLoading(true);setErro(null);try{const d=await api({acao:"cadastrar",...cadastro});setSucesso(d.existente?"Você já participa do programa.":"Cadastro no Programa de Indicação concluído.");setIndicadorId(d.indicadorId)}catch(e){setErro(e instanceof Error?e.message:"Erro")}finally{setLoading(false)}}
  async function consultar(e:React.FormEvent){e.preventDefault();setLoading(true);setErro(null);try{const d=await api({acao:"consultar",cpf:cpfConsulta});setResultados(d.indicacoes||[]);setConsultado(true)}catch(e){setErro(e instanceof Error?e.message:"Erro")}finally{setLoading(false)}}
  async function enviar(e:React.FormEvent){e.preventDefault();setLoading(true);setErro(null);setSucesso(null);try{const r=await fetch("/api/public/leads/indicacao",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({indicadorId,indicadorNome,indicadorTelefone,origem,indicados:indicados.map(i=>({nome:i.nome,whatsapp:i.whatsapp,tipoCredito:i.tipoCredito,valorCredito:i.valorCredito,observacao:i.observacao}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao enviar");setSucesso(`${d.count} indicação(ões) registrada(s).`);setIndicados([novoIndicado()]);if(!indicadorId){setConvidar(true);setCadastro(c=>({...c,nome:indicadorNome,telefone:indicadorTelefone}))}}catch(e){setErro(e instanceof Error?e.message:"Erro")}finally{setLoading(false)}}
  const podeEnviar=indicadorNome.trim().split(/\s+/).length>=2&&digitsOnlyPhone(indicadorTelefone).length>=10&&indicados.every(i=>i.nome.trim().split(/\s+/).length>=2&&digitsOnlyPhone(i.whatsapp).length>=10);
  const card="rounded-2xl border border-zinc-700/70 bg-zinc-900/60 p-6";
  return <div className="mx-auto max-w-3xl space-y-6 pb-24">
    <div className="grid gap-3 sm:grid-cols-3"><Button type="button" variant={aba==="indicar"?"gold":"outlineGold"} onClick={()=>trocar("indicar")}><Users className="mr-2 h-4 w-4"/>Fazer indicação</Button><Button type="button" variant={aba==="programa"?"gold":"outlineGold"} onClick={()=>trocar("programa")}><UserPlus className="mr-2 h-4 w-4"/>Programa de Indicação</Button><Button type="button" variant={aba==="visualizar"?"gold":"outlineGold"} onClick={()=>trocar("visualizar")}><Eye className="mr-2 h-4 w-4"/>Ver minhas indicações</Button></div>
    {erro&&<p className="rounded-lg bg-red-950/50 p-3 text-sm text-red-300">{erro}</p>}{sucesso&&<p className="rounded-lg bg-emerald-950/50 p-3 text-sm text-emerald-300">{sucesso}</p>}
    {aba==="programa"&&<form onSubmit={cadastrar} className={cn(card,"space-y-4")}><h2 className="text-xl font-bold text-white">Cadastrar no Programa de Indicação</h2><p className="text-sm text-zinc-400">CPF e PIX são usados para identificação e recebimento e não aparecem na consulta pública.</p><Campo label="Nome completo *"><Input required value={cadastro.nome} onChange={e=>setCadastro({...cadastro,nome:e.target.value})} className={surfaceInputDarkSlate}/></Campo><div className="grid gap-4 sm:grid-cols-2"><Campo label="CPF *"><Input required inputMode="numeric" value={cadastro.cpf} onChange={e=>setCadastro({...cadastro,cpf:formatCpfBrInput(e.target.value)})} className={surfaceInputDarkSlate}/></Campo><Campo label="Telefone *"><Input required inputMode="tel" value={cadastro.telefone} onChange={e=>setCadastro({...cadastro,telefone:formatWhatsappBrInput(e.target.value)})} className={surfaceInputDarkSlate}/></Campo></div><Campo label="Chave PIX *"><Input required value={cadastro.chavePix} onChange={e=>setCadastro({...cadastro,chavePix:e.target.value})} className={surfaceInputDarkSlate}/></Campo><Campo label="Empresa onde trabalha (opcional)"><Input value={cadastro.empresaTrabalho} onChange={e=>setCadastro({...cadastro,empresaTrabalho:e.target.value})} className={surfaceInputDarkSlate}/></Campo><Button disabled={loading} type="submit" variant="gold" className="w-full">{loading?"Salvando…":"Concluir cadastro"}</Button></form>}
    {aba==="visualizar"&&<form onSubmit={consultar} className={cn(card,"space-y-4")}><h2 className="text-xl font-bold text-white">Minhas indicações</h2><p className="text-sm text-zinc-400">Informe o CPF usado no Programa de Indicação.</p><Campo label="CPF *"><Input required inputMode="numeric" value={cpfConsulta} onChange={e=>setCpfConsulta(formatCpfBrInput(e.target.value))} className={surfaceInputDarkSlate}/></Campo><Button disabled={loading} type="submit" variant="gold" className="w-full">Visualizar</Button>{consultado&&<div className="space-y-3 pt-3"><p className="font-semibold text-white">{resultados.length} pessoa(s) indicada(s)</p>{resultados.length===0?<p className="text-sm text-zinc-400">Nenhuma indicação localizada.</p>:resultados.map(r=><div key={r.id} className="rounded-xl border border-zinc-700 bg-zinc-950/60 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-white">{r.nome}</strong><span className="rounded-full bg-amber-500/15 px-3 py-1 text-xs font-semibold text-amber-300">{STATUS[r.status]||r.status}</span></div><p className="mt-2 text-sm text-zinc-300">Valor contratado: <strong>{r.valorVenda?formatCurrency(r.valorVenda):"—"}</strong></p></div>)}</div>}</form>}
    {aba==="indicar"&&<form onSubmit={enviar} className="space-y-6"><section className={cn(card,"space-y-4")}><h2 className="text-xl font-bold text-white">Quem está indicando</h2><p className="text-sm text-zinc-400">Quem já participa pode localizar o cadastro por CPF ou telefone. Quem não participa informa apenas nome completo e telefone.</p><div className="grid gap-4 sm:grid-cols-2"><Campo label="CPF do indicador"><Input inputMode="numeric" value={buscaCpf} onChange={e=>setBuscaCpf(formatCpfBrInput(e.target.value))} className={surfaceInputDarkSlate}/></Campo><Campo label="Telefone do indicador *"><Input required inputMode="tel" value={indicadorTelefone} onChange={e=>{setIndicadorTelefone(formatWhatsappBrInput(e.target.value));setIndicadorId(null)}} className={surfaceInputDarkSlate}/></Campo></div><Button type="button" variant="outlineGold" disabled={loading||(!buscaCpf&&digitsOnlyPhone(indicadorTelefone).length<10)} onClick={localizar}>Localizar cadastro</Button><Campo label="Nome completo de quem indicou *"><Input required readOnly={Boolean(indicadorId)} value={indicadorNome} onChange={e=>setIndicadorNome(e.target.value)} className={surfaceInputDarkSlate}/></Campo></section>
      {indicados.map((ind,index)=><section key={ind.id} className={cn(card,"space-y-4")}><div className="flex justify-between"><h2 className="font-bold text-amber-200">Indicado {index+1}</h2>{indicados.length>1&&<button type="button" onClick={()=>setIndicados(x=>x.filter(v=>v.id!==ind.id))} className="text-sm text-red-300"><Trash2 className="inline h-4 w-4"/> Remover</button>}</div><Campo label="Nome completo *"><Input required value={ind.nome} onChange={e=>setIndicados(x=>x.map(v=>v.id===ind.id?{...v,nome:e.target.value}:v))} className={surfaceInputDarkSlate}/></Campo><Campo label="Telefone *"><Input required inputMode="tel" value={ind.whatsapp} onChange={e=>setIndicados(x=>x.map(v=>v.id===ind.id?{...v,whatsapp:formatWhatsappBrInput(e.target.value)}:v))} className={surfaceInputDarkSlate}/></Campo><Campo label="Tipo de crédito"><select value={ind.tipoCredito} onChange={e=>setIndicados(x=>x.map(v=>v.id===ind.id?{...v,tipoCredito:e.target.value}:v))} className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white"><option value="">Selecione…</option>{TIPOS_CREDITO_PUBLICO.map(t=><option key={t}>{t}</option>)}</select></Campo><Campo label="Valor desejado"><MoneyInput value={ind.valorCredito} onValueChange={v=>setIndicados(x=>x.map(i=>i.id===ind.id?{...i,valorCredito:v}:i))} className={surfaceInputDarkSlate}/></Campo><Campo label="Observação"><Textarea rows={2} value={ind.observacao} onChange={e=>setIndicados(x=>x.map(v=>v.id===ind.id?{...v,observacao:e.target.value}:v))} className={surfaceInputDarkSlate}/></Campo></section>)}
      <Button type="button" variant="outlineGold" className="w-full border-dashed" onClick={()=>setIndicados(x=>[...x,novoIndicado()])}><Plus className="mr-2 h-4 w-4"/>Adicionar outra indicação</Button><Button type="submit" variant="gold" className="w-full" disabled={loading||!podeEnviar}>{loading?"Enviando…":"Enviar indicações"}</Button>{convidar&&<div className={cn(card,"text-center")}><h3 className="font-bold text-white">Deseja participar do Programa de Indicação?</h3><p className="my-3 text-sm text-zinc-400">Cadastre CPF e PIX para acompanhar indicações e receber comissões.</p><Button type="button" variant="gold" onClick={()=>trocar("programa")}>Sim, quero participar</Button></div>}
    </form>}
  </div>;
}

function Campo({label,children}:{label:string;children:React.ReactNode}){return <div><Label className="font-bold text-white">{label}</Label><div className="mt-1">{children}</div></div>}
