"use client";

import Link from "next/link";
import { useState } from "react";
import { formatCpfBrInput, formatWhatsappBrInput } from "@/lib/utils/format";
import { MODELOS_PROGRAMA_PARCEIROS, type ModeloParceiroId } from "@/lib/parceiros/modelos-programa";
import { InstalarAppParceiroButton } from "@/components/public/instalar-app-parceiro-button";

const pilares = [
  ["Treinamento que acelera", "Produto, abordagem, objeções e método comercial para você entrar em ação com clareza."],
  ["Estrutura que sustenta", "Materiais, reuniões, backoffice, documentos, contratos e pós-venda para apoiar a operação."],
  ["Rede que gera negócios", "Encontros, eventos e conexões com pessoas que querem crescer comercialmente."],
  ["Autonomia com suporte", "Você escolhe a forma de participar e conta com a Master nas etapas estratégicas."],
];

const raconLandingCss = `
  .racon-parceiros { background: #ffffff; color: #0b2855; }
  .racon-parceiros [class*="bg-zinc-"] { background-color: #f7faff; }
  .racon-parceiros [class*="text-white"] { color: #0b2855; }
  .racon-parceiros [class*="text-zinc-"] { color: #385270; }
  .racon-parceiros [class*="text-amber"] { color: #0066cc; }
  .racon-parceiros [class*="border-white"] { border-color: #dbe7f5; }
  .racon-parceiros [class*="bg-amber"] { background-color: #0066cc; color: #ffffff; }
  .racon-parceiros [class*="bg-amber"] [class*="text-zinc-"] { color: #ffffff; }
  .racon-parceiros button[class*="bg-zinc-950"] { background-color: #0066cc !important; color: #ffffff !important; }
  .racon-parceiros .racon-hero { --visual-title: #ffffff; --visual-text: #eaf5ff; --visual-accent: #ffffff; background: linear-gradient(125deg, #004ca8 0%, #006dcc 55%, #0099dd 100%); }
  .racon-parceiros .racon-hero > div > p { color: #ffffff !important; }
  .racon-parceiros .racon-hero [class*="bg-zinc-"] { background-color: rgba(5, 41, 94, .28); }
  .racon-parceiros .racon-hero [class*="text-white"] { color: #ffffff; }
  .racon-parceiros .racon-hero [class*="text-zinc-"] { color: #e1efff; }
  .racon-parceiros .racon-hero [class*="text-amber"] { color: #b9e0ff; }
  .racon-parceiros .racon-hero [class*="bg-amber"] { background-color: #ffffff; color: #0066cc; }
  .racon-parceiros .racon-hero [class*="bg-amber"] [class*="text-zinc-"] { color: #0066cc; }
  .racon-parceiros .racon-hero .racon-hero-card { --visual-title: #0b2855; --visual-text: #385270; --visual-accent: #0066cc; background: #ffffff !important; color: #0b2855 !important; border-color: rgba(255,255,255,.75) !important; }
  .racon-parceiros .racon-hero .racon-hero-card-kicker,
  .racon-parceiros .racon-hero .racon-hero-card-link { color: #0066cc !important; }
  .racon-parceiros .racon-hero .racon-hero-card-title { color: #0b2855 !important; }
  .racon-parceiros .racon-hero .racon-hero-card-body { color: #385270 !important; }
  .racon-parceiros .racon-network { --visual-title: #ffffff; --visual-text: #eef8ff; --visual-accent: #ffffff; background: linear-gradient(135deg, #0055b8, #008fcf) !important; }
  .racon-parceiros .racon-network a { background: #ffffff !important; color: #005db8 !important; box-shadow: 0 8px 24px rgba(0, 48, 112, .2); }
  .racon-parceiros .racon-network a * { color: #005db8 !important; }
`;

function Cta({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) {
  return <Link href={href} className={`inline-flex min-h-12 items-center justify-center rounded-2xl px-6 py-3 text-center text-sm font-black transition ${secondary ? "border border-white/25 bg-white/5 text-white hover:bg-white/10" : "bg-amber-400 text-zinc-950 hover:-translate-y-0.5 hover:bg-amber-300"}`}>{children}</Link>;
}

export function ParceirosLandingClient({ racon = false, brandName = "Gauchinho Consórcios" }: { racon?: boolean; brandName?: string }) {
  return <main className={`overflow-hidden bg-zinc-950 text-white ${racon ? "racon-parceiros" : ""}`}>
    {racon ? <style>{raconLandingCss}</style> : null}
    <section className={`relative isolate border-b border-white/10 bg-[radial-gradient(circle_at_15%_15%,rgba(245,158,11,.23),transparent_32%),radial-gradient(circle_at_90%_35%,rgba(37,99,235,.20),transparent_34%)] ${racon ? "racon-hero" : ""}`}>
      <div className="mx-auto max-w-6xl px-5 py-20 sm:py-28">
        <p className="text-sm font-black tracking-[.18em] text-amber-400">{racon ? `${brandName.toUpperCase()} · PROGRAMA DE PARCEIROS` : "GAUCHINHO CONSÓRCIOS | RACON"}</p>
        <div className="mt-7 grid items-end gap-10 lg:grid-cols-[1.35fr_.65fr]">
          <div>
            <h1 className="max-w-4xl text-4xl font-black leading-[.98] sm:text-6xl lg:text-7xl">Transforme relacionamento em negócio com uma estrutura pronta para vender.</h1>
            <p className="mt-7 max-w-2xl text-lg leading-relaxed text-zinc-300">Escolha como quer participar: indicar oportunidades, gerar negócios ou construir sua própria operação comercial com o apoio da Master.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Cta href="#modelos">Conhecer os modelos de ganho</Cta><Cta href="/parceiros/cadastro?modelo=CONVERSAR_EQUIPE" secondary>Quero falar com a equipe</Cta></div>
            <div className="mt-7"><InstalarAppParceiroButton dark racon={racon} /></div>
          </div>
          <div className={`rounded-3xl border border-amber-300/30 bg-zinc-900/80 p-6 shadow-2xl shadow-amber-500/10 ${racon ? "racon-hero-card" : ""}`}>
            <p className={`text-sm font-bold text-amber-300 ${racon ? "racon-hero-card-kicker" : ""}`}>VOCÊ ESCOLHE O CAMINHO</p>
            <p className={`mt-4 text-3xl font-black ${racon ? "racon-hero-card-title" : ""}`}>Indicar. Gerar. Construir.</p>
            <p className={`mt-3 text-sm leading-relaxed text-zinc-300 ${racon ? "racon-hero-card-body" : ""}`}>Sua participação é reconhecida conforme o modelo, a operação validada e as regras comerciais vigentes.</p>
            <a href="#modelos" className={`mt-6 inline-flex font-bold text-amber-300 ${racon ? "racon-hero-card-link" : ""}`}>Ver comparativo completo ↓</a>
          </div>
        </div>
      </div>
    </section>

    <section className="mx-auto max-w-6xl px-5 py-20 sm:py-28">
      <div className="max-w-3xl"><p className="text-sm font-black tracking-[.16em] text-amber-400">MUITO ALÉM DA VENDA DE CONSÓRCIO</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">Você não começa sozinho.</h2><p className="mt-5 text-lg leading-relaxed text-zinc-300">O programa conecta relacionamento, eventos, indicações, vendas e pós-venda em uma rede organizada para transformar oportunidade em negócio real.</p></div>
      <div className="mt-10 grid gap-4 sm:grid-cols-2">{pilares.map(([titulo, texto], index) => <article key={titulo} className="rounded-3xl border border-white/10 bg-zinc-900 p-6"><span className="text-2xl font-black text-amber-400">0{index + 1}</span><h3 className="mt-5 text-xl font-black">{titulo}</h3><p className="mt-3 leading-relaxed text-zinc-400">{texto}</p></article>)}</div>
    </section>

    <section id="modelos" className="border-y border-white/10 bg-zinc-900/60 px-5 py-20 sm:py-28">
      <div className="mx-auto max-w-6xl"><div className="max-w-3xl"><p className="text-sm font-black tracking-[.16em] text-amber-400">ESCOLHA SEU MODELO</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">Quanto maior sua atuação, maior sua participação.</h2><p className="mt-5 text-zinc-300">Conheça as modalidades, compare o potencial e encontre a forma de começar que combina com seu momento.</p></div>
        <div className="mt-10 grid gap-5 lg:grid-cols-3">{MODELOS_PROGRAMA_PARCEIROS.map((m, index) => <article key={m.id} className={`flex flex-col rounded-3xl border p-7 ${index === 1 ? "border-amber-400 bg-amber-400/10" : "border-white/10 bg-zinc-950"}`}><p className="text-sm font-black text-amber-400">{m.ganho} DA BASE LÍQUIDA</p><h3 className="mt-4 text-3xl font-black">{m.nome}</h3><p className="mt-3 min-h-18 text-zinc-300">{m.resumo}</p><div className="mt-6 border-y border-white/10 py-4"><p className="font-bold text-white">{m.meta}</p></div><ul className="mt-5 space-y-3 text-sm text-zinc-300">{m.vantagens.map((vantagem) => <li key={vantagem} className="flex gap-2"><span className="text-amber-400">✓</span>{vantagem}</li>)}</ul><div className="mt-8"><Cta href={`/parceiros/${m.slug}`}>Ver ganhos e condições</Cta></div></article>)}</div>
        <div className="mt-10 overflow-x-auto rounded-3xl border border-white/10 bg-zinc-950 p-2"><table className="min-w-[720px] w-full text-left text-sm"><thead className="text-amber-300"><tr><th className="p-4">Modelo</th><th className="p-4">Participação</th><th className="p-4">Para quem</th><th className="p-4">Meta</th></tr></thead><tbody>{MODELOS_PROGRAMA_PARCEIROS.map((m) => <tr key={m.id} className="border-t border-white/10 text-zinc-300"><td className="p-4 font-bold text-white">{m.nome}</td><td className="p-4">{m.ganho} da base líquida</td><td className="p-4">{m.publico[0]}</td><td className="p-4">{m.meta}</td></tr>)}</tbody></table></div>
      </div>
    </section>

    <section className="mx-auto grid max-w-6xl gap-8 px-5 py-20 sm:grid-cols-2 sm:py-28"><div className={`rounded-3xl bg-amber-400 p-8 text-zinc-950 ${racon ? "racon-network" : ""}`}><p className="text-sm font-black tracking-[.16em]">NETWORK DE NEGÓCIOS</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">Toda terça-feira, às 19h, uma nova oportunidade de conexão.</h2><p className="mt-5 leading-relaxed">Parceiros, empresários, vendedores, corretores e pessoas com visão de crescimento reunidos para gerar conversas, conexões e negócios.</p><div className="mt-7"><Cta href="/parceiros/cadastro?modelo=CONVERSAR_EQUIPE">Quero participar do próximo encontro</Cta></div></div><div className="rounded-3xl border border-white/10 bg-zinc-900 p-8"><p className="text-sm font-black tracking-[.16em] text-amber-400">O QUE A ESTRUTURA ENTREGA</p><ul className="mt-6 grid gap-4 text-zinc-200">{["Treinamento de produto, abordagem e objeções", "Material digital e impresso", "Suporte em reuniões e vendas estratégicas", "Backoffice de cadastro, documentos e contratos", "Pós-venda e acompanhamento de cotas", "Gestão de leads e oportunidades"].map((item) => <li key={item} className="flex gap-3"><span className="text-amber-400">✦</span>{item}</li>)}</ul></div></section>

    <section className="border-t border-white/10 bg-zinc-900 px-5 py-20 text-center"><div className="mx-auto max-w-3xl"><p className="text-sm font-black tracking-[.16em] text-amber-400">SEU PRÓXIMO PASSO</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Sua rede já tem valor. Vamos transformá-la em oportunidade?</h2><p className="mt-6 text-lg text-zinc-300">Cadastre-se, escolha a modalidade que mais combina com seu momento e receba a orientação da equipe para começar.</p><div className="mt-9"><Cta href="/parceiros/cadastro?modelo=CONVERSAR_EQUIPE">Quero me cadastrar como parceiro</Cta></div><p className="mt-8 text-xs leading-relaxed text-zinc-500">Os valores apresentados nas simulações são estimativos e dependem de regras comerciais vigentes, recebimento efetivo de comissão, validação da operação, cancelamentos, inadimplência e estornos.</p></div></section>
  </main>;
}

function escolhaClasse(ativo: boolean) { return `rounded-2xl border p-4 text-left text-sm font-bold transition ${ativo ? "border-amber-500 bg-amber-50 text-amber-950" : "border-zinc-200 bg-white hover:border-amber-300"}`; }

const opcoesModelo = [...MODELOS_PROGRAMA_PARCEIROS, { id: "CONVERSAR_EQUIPE", nome: "Ainda não sei — quero conversar com a equipe" }] as const;

export function CadastroParceiroClient({ modeloInicial, racon = false, brandName = "Gauchinho Consórcios" }: { modeloInicial: ModeloParceiroId | "CONVERSAR_EQUIPE"; racon?: boolean; brandName?: string }) {
  const [modelo, setModelo] = useState<ModeloParceiroId | "CONVERSAR_EQUIPE">(modeloInicial);
  const [step, setStep] = useState(0); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [tipoPix, setTipoPix] = useState("CELULAR"); const [cadastroAtualizado, setCadastroAtualizado] = useState(false); const [consultorReaproveitado, setConsultorReaproveitado] = useState(false); const [senhaInicialCriada, setSenhaInicialCriada] = useState(false);
  const [form, setForm] = useState({ nome: "", whatsapp: "", email: "", cpf: "", cidade: "", estado: "", profissao: "", chavePix: "", observacao: "", jaVendeConsorcio: "", redeRelacionamento: [] as string[], potencialMensal: "", interesseNetwork: "" });
  const update = (k: keyof typeof form, v: string) => setForm((x) => ({ ...x, [k]: v }));
  const toggleRede = (item: string) => setForm((x) => ({ ...x, redeRelacionamento: x.redeRelacionamento.includes(item) ? x.redeRelacionamento.filter((atual) => atual !== item) : [...x.redeRelacionamento, item] }));
  const podeAvancar = () => (step === 0 ? form.nome.trim().split(/\s+/).length >= 2 && form.whatsapp.replace(/\D/g, "").length >= 10 : step === 1 ? form.cpf.replace(/\D/g, "").length === 11 && form.email.includes("@") : step === 2 ? Boolean(form.cidade && form.estado && form.profissao && form.jaVendeConsorcio) : step === 3 ? Boolean(modelo && form.potencialMensal && form.interesseNetwork) : form.chavePix.trim().length >= 3);
  function avancar() { if (!podeAvancar()) { setMessage("Complete as opções desta etapa para continuar."); return; } setMessage(""); setStep((atual) => atual + 1); }
  async function submit() { if (!podeAvancar()) { setMessage("Informe sua chave PIX para concluir."); return; } setLoading(true); setMessage(""); try { const utm = new URLSearchParams(window.location.search); const r = await fetch("/api/public/programa-indicacao", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ acao: "cadastrar_parceiro", ...form, tipoChavePix: tipoPix, modeloInteresse: modelo, paginaOrigem: window.location.pathname, utmSource: utm.get("utm_source"), utmMedium: utm.get("utm_medium"), utmCampaign: utm.get("utm_campaign") }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Não foi possível concluir."); setCadastroAtualizado(Boolean(d.atualizado)); setConsultorReaproveitado(Boolean(d.consultorReaproveitado)); setSenhaInicialCriada(Boolean(d.senhaInicialCriada || (!d.atualizado && !d.consultorReaproveitado))); setStep(99); } catch (erro) { setMessage(erro instanceof Error ? erro.message : "Erro ao cadastrar"); } finally { setLoading(false); } }
  if (step === 99) return <main className={`min-h-screen bg-zinc-950 px-5 py-20 text-center text-white ${racon ? "racon-parceiros" : ""}`}>{racon ? <style>{raconLandingCss}</style> : null}<section className="mx-auto max-w-xl rounded-3xl border border-amber-400/30 bg-zinc-900 p-8"><p className="font-black tracking-[.16em] text-amber-400">{consultorReaproveitado ? "CONSULTOR HABILITADO" : cadastroAtualizado ? "CADASTRO ATUALIZADO" : "CADASTRO RECEBIDO"}</p><h1 className="mt-4 text-4xl font-black">Você já começa no Nível 1.</h1><p className="mt-5 leading-relaxed text-zinc-300">{consultorReaproveitado ? "Reaproveitamos seu cadastro de consultor, sem criar um novo participante." : cadastroAtualizado ? "Atualizamos seus dados comerciais e PIX. Sua senha de acesso existente foi preservada." : "Seu acesso como Gerador de Possibilidades está pronto."} {senhaInicialCriada ? "Sua senha inicial são os últimos 6 dígitos do CPF." : ""} {modelo !== "GERADOR_POSSIBILIDADES" && modelo !== "CONVERSAR_EQUIPE" ? `A modalidade escolhida foi enviada para análise da equipe ${brandName}.` : "Nossa equipe entrará em contato para apoiar seus próximos passos."}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Cta href="/app-indicador/login">Abrir meu painel mobile</Cta><Cta href="/parceiros" secondary>Voltar ao programa</Cta></div><p className="mt-8 text-sm text-zinc-400">Também convidamos você para o Network de Negócios: toda terça-feira, às 19h.</p></section></main>;
  const titulos = ["Vamos começar pela sua apresentação", "Agora crie seu acesso ao painel", "Conte um pouco sobre seu momento", "Como você quer participar?", "Cadastre seu PIX para receber suas comissões"];
  return <main className={`min-h-screen bg-zinc-950 px-5 py-12 text-zinc-950 ${racon ? "racon-parceiros" : ""}`}>{racon ? <style>{raconLandingCss}</style> : null}<section className="mx-auto max-w-2xl overflow-hidden rounded-[2rem] bg-white shadow-2xl"><div className="bg-zinc-900 px-7 py-6 text-white"><Link href="/parceiros" className="text-sm font-bold text-amber-300">← Conhecer as modalidades</Link><p className="mt-5 text-sm font-black tracking-[.12em] text-amber-400">CADASTRO CONVERSACIONAL · {step + 1} DE 5</p><h1 className="mt-2 text-3xl font-black">{titulos[step]}</h1><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-400 transition-all" style={{ width: `${((step + 1) / 5) * 100}%` }} /></div></div>
      <div className="p-7 sm:p-9">{step === 0 && <><p className="text-zinc-600">Para a equipe falar com você e entender como sua rede pode gerar oportunidades.</p><input autoFocus placeholder="Seu nome completo" value={form.nome} onChange={(e) => update("nome", e.target.value)} className="mt-6 w-full rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /><input placeholder="Seu WhatsApp com DDD" inputMode="tel" value={form.whatsapp} onChange={(e) => update("whatsapp", formatWhatsappBrInput(e.target.value))} className="mt-3 w-full rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /></>}
        {step === 1 && <><p className="text-zinc-600">Você acessará suas indicações e comissões pelo celular usando seu CPF.</p><input autoFocus placeholder="CPF" inputMode="numeric" value={form.cpf} onChange={(e) => update("cpf", formatCpfBrInput(e.target.value))} className="mt-6 w-full rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /><input placeholder="Seu melhor e-mail" type="email" value={form.email} onChange={(e) => update("email", e.target.value)} className="mt-3 w-full rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /><p className="mt-3 rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-950">Sua senha inicial serão os últimos 6 dígitos do CPF. Se você já for consultor cadastrado, sua senha atual será preservada.</p></>}
        {step === 2 && <><p className="text-zinc-600">Assim entendemos melhor seu perfil para orientar o melhor caminho.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><input placeholder="Cidade" value={form.cidade} onChange={(e) => update("cidade", e.target.value)} className="rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /><input placeholder="Estado (ex.: MT)" maxLength={2} value={form.estado} onChange={(e) => update("estado", e.target.value.toUpperCase())} className="rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /></div><input placeholder="Sua profissão ou atividade atual" value={form.profissao} onChange={(e) => update("profissao", e.target.value)} className="mt-3 w-full rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /><p className="mt-6 font-black">Você já vende consórcio?</p><div className="mt-3 grid gap-2 sm:grid-cols-3">{["Sim", "Não", "Já vendi"].map((item) => <button type="button" key={item} onClick={() => update("jaVendeConsorcio", item)} className={escolhaClasse(form.jaVendeConsorcio === item)}>{item}</button>)}</div></>}
        {step === 3 && <><p className="text-zinc-600">Escolha a modalidade desejada. Se pedir um nível acima, sua solicitação entra em análise; sua entrada já começa no Nível 1.</p><div className="mt-6 grid gap-2">{opcoesModelo.map((item) => <button type="button" key={item.id} onClick={() => setModelo(item.id)} className={escolhaClasse(modelo === item.id)}>{item.nome}{"ganho" in item && <span className="float-right text-amber-700">{item.ganho}</span>}</button>)}</div><p className="mt-6 font-black">Com quais redes você mais se relaciona?</p><div className="mt-3 flex flex-wrap gap-2">{["Imóveis", "Veículos", "Empresários", "Investidores", "Agronegócio", "Vendas em geral"].map((item) => <button type="button" key={item} onClick={() => toggleRede(item)} className={`rounded-full border px-4 py-2 text-sm font-bold ${form.redeRelacionamento.includes(item) ? "border-amber-500 bg-amber-100" : "border-zinc-300"}`}>{item}</button>)}</div><p className="mt-6 font-black">Quanto acredita que consegue movimentar por mês?</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{["Até R$ 500 mil", "R$ 500 mil a R$ 1 milhão", "R$ 1 milhão a R$ 3 milhões", "Acima de R$ 3 milhões"].map((item) => <button type="button" key={item} onClick={() => update("potencialMensal", item)} className={escolhaClasse(form.potencialMensal === item)}>{item}</button>)}</div><p className="mt-6 font-black">Quer participar do Network de terça-feira, às 19h?</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{["Sim, quero participar", "Quero saber mais"].map((item) => <button type="button" key={item} onClick={() => update("interesseNetwork", item)} className={escolhaClasse(form.interesseNetwork === item)}>{item}</button>)}</div></>}
        {step === 4 && <><p className="text-emerald-700">Cadastre seu PIX para receber suas comissões automaticamente.</p><p className="mt-6 font-black">Tipo de chave PIX</p><div className="mt-3 grid grid-cols-2 gap-2">{["CELULAR", "E-MAIL", "CPF", "ALEATÓRIA"].map((item) => <button type="button" key={item} onClick={() => setTipoPix(item === "ALEATÓRIA" ? "ALEATORIA" : item)} className={escolhaClasse(tipoPix === (item === "ALEATÓRIA" ? "ALEATORIA" : item))}>{item}</button>)}</div><input autoFocus placeholder={`Digite sua chave PIX ${tipoPix.toLowerCase()}`} value={form.chavePix} onChange={(e) => update("chavePix", e.target.value)} className="mt-4 w-full rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /><textarea placeholder="Quer deixar uma observação? (opcional)" value={form.observacao} onChange={(e) => update("observacao", e.target.value)} className="mt-3 min-h-28 w-full rounded-2xl border border-zinc-300 p-4 outline-none focus:border-amber-500" /></>}
        {message && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{message}</p>}<div className="mt-8 flex gap-3">{step > 0 && <button type="button" onClick={() => { setMessage(""); setStep((atual) => atual - 1); }} className="rounded-2xl border border-zinc-300 px-5 py-4 font-black">Voltar</button>}<button type="button" disabled={loading} onClick={step === 4 ? submit : avancar} className="flex-1 rounded-2xl bg-zinc-950 px-5 py-4 font-black text-white transition hover:bg-zinc-800 disabled:opacity-50">{loading ? "Enviando…" : step === 4 ? "Enviar cadastro e falar com a equipe" : "Continuar"}</button></div></div>
    </section></main>;
}
