"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { formatCpfBrInput, formatWhatsappBrInput } from "@/lib/utils/format";
import { InstalarAppParceiroButton } from "@/components/public/instalar-app-parceiro-button";

export const MODELOS = [
  { id: "MICROFRANQUEADO", slug: "microfranqueado", nome: "Microfranqueado", ganho: "50%", meta: "Meta anual de R$ 12 milhões", resumo: "Para quem quer construir sua própria operação comercial.", vantagens: ["Estrutura pronta e suporte da Master", "Treinamento comercial e operacional", "Eventos e apoio em vendas estratégicas"] },
  { id: "GERADOR_NEGOCIOS", slug: "gerador-de-negocios", nome: "Gerador de Negócios", ganho: "25%", meta: "Meta anual de R$ 6 milhões", resumo: "Para quem vende, reúne pessoas e transforma conexões em negócios.", vantagens: ["Apoio em reuniões e apresentações", "Network semanal e materiais comerciais", "Você pode vender ou encaminhar para a equipe"] },
  { id: "GERADOR_POSSIBILIDADES", slug: "gerador-de-possibilidades", nome: "Gerador de Possibilidades", ganho: "12,5%", meta: "Sem meta obrigatória", resumo: "Para quem quer indicar oportunidades sem precisar vender.", vantagens: ["Cadastro simples de indicações pelo celular", "Acompanhamento do andamento e das comissões", "Sem obrigação de reunião ou fechamento"] },
] as const;
export type ModeloId = (typeof MODELOS)[number]["id"];

export function ParceirosLandingClient() {
  useEffect(() => { if ("serviceWorker" in navigator) void navigator.serviceWorker.register("/sw.js"); }, []);
  return <main className="min-h-screen bg-zinc-950 text-white"><section className="mx-auto max-w-5xl px-5 py-20 text-center"><p className="font-bold text-amber-400">GAUCHINHO CONSÓRCIOS | RACON</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">Faça parte da nossa rede de negócios.</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-zinc-300">Conheça as vantagens de cada modalidade e escolha o caminho que combina com seu momento.</p><div className="mt-8"><InstalarAppParceiroButton dark /></div></section><section className="mx-auto grid max-w-5xl gap-4 px-5 pb-20 md:grid-cols-3">{MODELOS.map((m) => <Link key={m.id} href={`/parceiros/${m.slug}`} className="group rounded-3xl border border-zinc-700 p-7 transition hover:-translate-y-1 hover:border-amber-400 hover:bg-amber-400/10"><b className="text-2xl">{m.nome}</b><p className="mt-4 text-4xl font-black text-amber-400">{m.ganho}</p><p className="mt-2 text-zinc-300">{m.meta}</p><p className="mt-5 text-sm text-zinc-400">{m.resumo}</p><span className="mt-6 inline-block font-bold text-amber-400">Ver vantagens e condições →</span></Link>)}</section></main>;
}

export function CadastroParceiroClient({ modeloInicial }: { modeloInicial: ModeloId }) {
  const [modelo] = useState(modeloInicial); const [step, setStep] = useState(0); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [tipoPix, setTipoPix] = useState("CELULAR");
  const [form, setForm] = useState({ nome:"", whatsapp:"", email:"", cpf:"", senha:"", cidade:"", profissao:"", chavePix:"", observacao:"" });
  const update = (k: keyof typeof form, v: string) => setForm(x => ({ ...x, [k]: v }));
  async function submit() { setLoading(true); setMessage(""); try { const r = await fetch("/api/public/programa-indicacao", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ acao:"cadastrar_parceiro", ...form, tipoChavePix:tipoPix, modeloInteresse:modelo }) }); const d=await r.json(); if(!r.ok) throw new Error(d.error || "Não foi possível concluir."); setStep(99); } catch(e) { setMessage(e instanceof Error ? e.message : "Erro ao cadastrar"); } finally { setLoading(false); } }
  if(step===99) return <main className="mx-auto max-w-md px-5 py-20 text-center"><h1 className="text-3xl font-black">Cadastro concluído!</h1><p className="mt-4 text-zinc-600">Você entrou no Nível 1: Gerador de Possibilidades. {modelo!=="GERADOR_POSSIBILIDADES" ? "Sua escolha de modalidade está em análise pela equipe Gauchinho." : ""}</p><Link className="mt-8 inline-block rounded-2xl bg-amber-500 px-6 py-4 font-bold text-zinc-950" href="/app-indicador/login">Abrir meu app de indicações</Link></main>;
  return <main className="min-h-screen bg-zinc-950 px-5 py-12 text-zinc-900"><section className="mx-auto max-w-md rounded-3xl bg-white p-7"><p className="font-bold text-amber-700">Cadastro rápido · {step+1} de 3</p>{step===0&&<><h1 className="mt-3 text-3xl font-black">Vamos começar</h1><p className="mt-2 text-sm text-zinc-600">Nome e WhatsApp para a equipe falar com você.</p><input autoFocus placeholder="Nome completo" value={form.nome} onChange={e=>update("nome",e.target.value)} className="mt-6 w-full rounded-2xl border p-4"/><input placeholder="WhatsApp com DDD" inputMode="tel" value={form.whatsapp} onChange={e=>update("whatsapp",formatWhatsappBrInput(e.target.value))} className="mt-3 w-full rounded-2xl border p-4"/></>}{step===1&&<><h1 className="mt-3 text-3xl font-black">Crie seu acesso</h1><p className="mt-2 text-sm text-zinc-600">Você usará CPF e senha para entrar no app.</p><input placeholder="CPF" inputMode="numeric" value={form.cpf} onChange={e=>update("cpf",formatCpfBrInput(e.target.value))} className="mt-6 w-full rounded-2xl border p-4"/><input placeholder="E-mail" type="email" value={form.email} onChange={e=>update("email",e.target.value)} className="mt-3 w-full rounded-2xl border p-4"/><input placeholder="Senha (mínimo 8 caracteres)" type="password" value={form.senha} onChange={e=>update("senha",e.target.value)} className="mt-3 w-full rounded-2xl border p-4"/></>}{step===2&&<><h1 className="mt-3 text-3xl font-black">Complete seu perfil</h1><input placeholder="Cidade" value={form.cidade} onChange={e=>update("cidade",e.target.value)} className="mt-6 w-full rounded-2xl border p-4"/><input placeholder="Profissão" value={form.profissao} onChange={e=>update("profissao",e.target.value)} className="mt-3 w-full rounded-2xl border p-4"/><p className="mt-6 font-bold text-emerald-700">Cadastre seu PIX para receber suas comissões automaticamente.</p><p className="mt-2 text-sm font-semibold">Tipo de chave PIX</p><div className="mt-2 grid grid-cols-2 gap-2">{["CELULAR","E-MAIL","CPF","ALEATORIA"].map(t=><button type="button" key={t} onClick={()=>setTipoPix(t)} className={`rounded-xl border px-3 py-3 text-sm font-bold ${tipoPix===t?"border-emerald-600 bg-emerald-50 text-emerald-800":""}`}>{t}</button>)}</div><input placeholder={`Chave PIX ${tipoPix.toLowerCase()}`} value={form.chavePix} onChange={e=>update("chavePix",e.target.value)} className="mt-3 w-full rounded-2xl border p-4"/></>}{message&&<p className="mt-4 text-sm font-semibold text-red-700">{message}</p>}<div className="mt-7 flex gap-3">{step>0&&<button onClick={()=>setStep(step-1)} className="rounded-2xl border px-5 py-4 font-bold">Voltar</button>}<button disabled={loading} onClick={()=>step<2?setStep(step+1):submit()} className="flex-1 rounded-2xl bg-zinc-950 px-5 py-4 font-bold text-white">{loading?"Enviando…":step===2?"Concluir cadastro":"Continuar"}</button></div></section></main>;
}
