"use client";
import { useRef, useState } from "react";
import { ContactRound, FileUp, UserPlus } from "lucide-react";
import { saveContactsAction, sendContactToLeadAction, updateContactAction, type ContactInput } from "./actions";

type Contact = ContactInput & { id: string; telefone_normalizado: string };
function parseCsv(text: string): ContactInput[] { const lines = text.split(/\r?\n/).filter(Boolean); const headers = lines[0].split(/[;,]/).map((x) => x.trim().toLowerCase()); return lines.slice(1).map((line) => { const vals = line.split(/[;,]/).map((x) => x.trim().replace(/^"|"$/g, "")); const get = (...names: string[]) => vals[headers.findIndex((h) => names.includes(h))] ?? ""; return { nome: get("nome", "name", "nome completo"), telefone: get("telefone", "phone", "celular", "whatsapp"), email: get("email", "e-mail"), empresa: get("empresa", "company"), profissao: get("profissão", "profissao", "cargo", "occupation") }; }); }
function parseVcf(text: string): ContactInput[] { const unfolded = text.replace(/\r?\n[ \t]/g, ""); return unfolded.split(/BEGIN:VCARD/i).slice(1).map((card) => { const phones = [...card.matchAll(/(?:^|\n)(?:item\d+\.)?TEL(?:;[^:]*)?:([^\r\n]+)/gi)].map((m) => m[1].trim()); return { nome: card.match(/(?:^|\n)FN(?:;[^:]*)?:([^\r\n]+)/i)?.[1]?.trim() ?? "", telefone: phones.find((p) => p) ?? "", email: card.match(/(?:^|\n)EMAIL(?:;[^:]*)?:([^\r\n]+)/i)?.[1]?.trim() ?? "", empresa: card.match(/(?:^|\n)ORG(?:;[^:]*)?:([^\r\n]+)/i)?.[1]?.trim().replace(/;$/, "") ?? "", profissao: card.match(/(?:^|\n)TITLE(?:;[^:]*)?:([^\r\n]+)/i)?.[1]?.trim() ?? "" }; }).filter((x) => x.telefone); }
export default function ContactsClient({ initialContacts }: { initialContacts: Contact[] }) { const [contacts, setContacts] = useState(initialContacts); const [msg, setMsg] = useState(""); const input = useRef<HTMLInputElement>(null);
  async function importFile(file?: File) { if (!file) return; const parsed = file.name.toLowerCase().endsWith(".vcf") ? parseVcf(await file.text()) : parseCsv(await file.text()); const result = await saveContactsAction(parsed); setMsg(result.ok ? `${result.count} contatos importados${result.duplicatesIgnored ? `; ${result.duplicatesIgnored} repetidos foram consolidados.` : "."}` : result.error ?? "Erro"); if (result.ok) location.reload(); }
  async function lead(id: string) { const result = await sendContactToLeadAction(id); setMsg(result.ok ? "Contato enviado para Novo lead com você como responsável." : result.error ?? "Erro"); }
  async function edit(contact: Contact) { const empresa = window.prompt("Empresa", contact.empresa ?? ""); const profissao = window.prompt("Profissão", contact.profissao ?? ""); if (empresa === null || profissao === null) return; await updateContactAction(contact.id, { ...contact, empresa, profissao }); setContacts((old) => old.map((x) => x.id === contact.id ? { ...x, empresa, profissao } : x)); }
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Meus contatos</h1><p className="text-sm opacity-70">Somente contatos telefônicos importados por você nesta empresa.</p></div><><input ref={input} hidden type="file" accept=".csv,.vcf,text/csv,text/vcard" onChange={(e) => importFile(e.target.files?.[0])}/><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white" onClick={() => input.current?.click()}><FileUp className="mr-2 inline h-4 w-4"/>Importar CSV ou VCF</button></></div>{msg && <div className="rounded-lg bg-emerald-500/15 p-3 text-sm text-emerald-700">{msg}</div>}<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Nome</th><th className="p-3">Telefone</th><th className="p-3">Empresa</th><th className="p-3">Profissão</th><th className="p-3">Ações</th></tr></thead><tbody>{contacts.map((c) => <tr key={c.id} className="border-t"><td className="p-3 font-medium"><ContactRound className="mr-2 inline h-4 w-4"/>{c.nome}</td><td className="p-3">{c.telefone}</td><td className="p-3">{c.empresa || "—"}</td><td className="p-3">{c.profissao || "—"}</td><td className="p-3"><button className="mr-3 text-blue-600 hover:underline" onClick={() => edit(c)}>Editar</button><button className="text-emerald-600 hover:underline" onClick={() => lead(c.id)}><UserPlus className="mr-1 inline h-4 w-4"/>Enviar para lead</button></td></tr>)}</tbody></table>{!contacts.length && <p className="p-8 text-center text-slate-500">Importe um CSV ou VCF para começar.</p>}</div></div>;
}
