"use client";
import { useState, useTransition } from "react";
import { X, Save, Plus } from "lucide-react";
import type { LeadListRow, CrmFunilEtapaRow } from "@/lib/crm/types";
import { updateLeadAction } from "@/app/admin/leads/actions";

export function CrmLeadEditModal({ lead, etapas, onClose, onSaved }: { lead: LeadListRow; etapas: CrmFunilEtapaRow[]; onClose: () => void; onSaved: (lead: LeadListRow) => void }) {
  const [tags, setTags] = useState(lead.tags ?? []); const [tag, setTag] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, start] = useTransition();
  const addTag = () => { const value = tag.trim().replace(/^#/, ""); if (value && !tags.includes(value)) setTags([...tags, value].slice(0, 12)); setTag(""); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div role="dialog" aria-modal="true" className="flex max-h-[calc(100dvh-2rem)] w-full max-w-lg flex-col rounded-2xl border border-zinc-700 bg-zinc-950 p-5 text-zinc-100 shadow-2xl">
    <div className="mb-4 flex justify-between"><div><h2 className="text-lg font-bold">Editar lead</h2><p className="text-xs text-zinc-500">Dados, observações e tags</p></div><button onClick={onClose}><X className="h-5 w-5 text-zinc-400" /></button></div>
    <form className="space-y-3 overflow-y-auto pr-1" onSubmit={(e) => { e.preventDefault(); const form = new FormData(e.currentTarget); form.set("tags", tags.join(",")); start(async () => { try { await updateLeadAction(lead.id, form); onSaved({ ...lead, nome: String(form.get("nome")), whatsapp: String(form.get("whatsapp")) || null, email: String(form.get("email")) || null, observacoes: String(form.get("observacoes")) || null, valor_estimado: Number(form.get("valor_estimado")) || null, valor_credito: Number(form.get("valor_estimado")) || null, valor_parcela: Number(form.get("valor_parcela")) || null, tags }); } catch (err) { setError(err instanceof Error ? err.message : "Erro ao salvar"); } }); }}>
      <input type="hidden" name="cidade" value={lead.cidade ?? ""} /><input type="hidden" name="origem" value={lead.origem ?? ""} /><input type="hidden" name="tipo_interesse" value={lead.tipo_interesse ?? ""} /><input type="hidden" name="produto_interesse" value={lead.produto_interesse ?? ""} /><input type="hidden" name="evento_id" value={lead.evento_id ?? ""} /><input type="hidden" name="evento_nome" value={lead.evento_nome ?? ""} /><input type="hidden" name="status" value={lead.status} /><input type="hidden" name="temperatura" value={lead.temperatura ?? ""} /><input type="hidden" name="proxima_acao" value={lead.proxima_acao ?? ""} /><input type="hidden" name="data_proxima_acao" value={lead.data_proxima_acao ?? ""} /><input type="hidden" name="srd_responsavel_id" value={lead.srd_responsavel_id ?? ""} /><input type="hidden" name="srd_responsavel_nome" value={lead.srd_responsavel_nome ?? ""} />
      <div className="grid grid-cols-2 gap-3"><label className="text-xs text-zinc-400">Nome<input name="nome" defaultValue={lead.nome} required className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm" /></label><label className="text-xs text-zinc-400">Etapa<select name="etapa_id" defaultValue={lead.etapa_id ?? ""} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm">{etapas.map((e) => <option key={e.id} value={e.id}>{e.nome}</option>)}</select></label></div>
      <div className="grid grid-cols-2 gap-3"><label className="text-xs text-zinc-400">WhatsApp<input name="whatsapp" defaultValue={lead.whatsapp ?? ""} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm" /></label><label className="text-xs text-zinc-400">E-mail<input name="email" type="email" defaultValue={lead.email ?? ""} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm" /></label></div>
      <div className="grid grid-cols-2 gap-3"><label className="text-xs text-zinc-400">Crédito pretendido (R$)<input name="valor_estimado" type="number" min="0" step="0.01" defaultValue={lead.valor_credito ?? lead.valor_estimado ?? ""} placeholder="Ex.: 150000" className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm" /></label><label className="text-xs text-zinc-400">Parcela mensal (R$)<input name="valor_parcela" type="number" min="0" step="0.01" defaultValue={lead.valor_parcela ?? ""} placeholder="Quanto pode pagar" className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm" /></label></div>
      <label className="block text-xs text-zinc-400">Observações<textarea name="observacoes" defaultValue={lead.observacoes ?? ""} rows={4} className="mt-1 w-full resize-none rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm" /></label>
      <div><span className="text-xs text-zinc-400">Tags</span><div className="mt-1 flex flex-wrap gap-1.5">{tags.map((t) => <button type="button" key={t} onClick={() => setTags(tags.filter((x) => x !== t))} className="rounded-full bg-cyan-500/15 px-2 py-1 text-xs text-cyan-300">#{t} ×</button>)}<input value={tag} onChange={(e) => setTag(e.target.value)} onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addTag())} placeholder="nova tag" className="min-w-28 flex-1 rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs" /><button type="button" onClick={addTag} className="rounded-lg bg-zinc-800 px-2"><Plus className="h-4 w-4" /></button></div></div>
      {error && <p className="text-xs text-red-400">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg px-3 py-2 text-sm text-zinc-400">Cancelar</button><button disabled={pending} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold"><Save className="h-4 w-4" />{pending ? "Salvando..." : "Salvar"}</button></div>
    </form></div></div>;
}
